# Generated by Django 5.0.1 on 2024-01-24 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elevenlabs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElevenLabs',
        ),
    ]
