# Generated by Django 5.0.1 on 2024-01-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Elevenlabs', '0002_delete_elevenlabs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevenData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.CharField(max_length=2500)),
                ('date_text', models.CharField(max_length=2500)),
            ],
        ),
    ]
